#ifndef A2_SIMPLENAVIGATOR_V1_0_CPP_1_SRC_MATRIXPATH_MATRIXMATH_H_
#define A2_SIMPLENAVIGATOR_V1_0_CPP_1_SRC_MATRIXPATH_MATRIXMATH_H_

namespace s21 {

class MatrixMath {

};

} // s21

#endif //A2_SIMPLENAVIGATOR_V1_0_CPP_1_SRC_MATRIXPATH_MATRIXMATH_H_
