#ifndef A2_SIMPLENAVIGATOR_V1_0_CPP_1_SRC_GRAPHALGORITHMS_LEASTSPANNINGTREEENGINE_LEASTSPANNINGTREEENGINE_H_
#define A2_SIMPLENAVIGATOR_V1_0_CPP_1_SRC_GRAPHALGORITHMS_LEASTSPANNINGTREEENGINE_LEASTSPANNINGTREEENGINE_H_
#include <vector>

#include "Graph/Graph.h"

namespace s21 {

class LeastSpanningTreeEngine {
 public:
  [[nodiscard]] std::vector<std::vector<int>> GetLeastSpanningTree(
      const Graph &graph);
};

}  // namespace s21

#endif  // A2_SIMPLENAVIGATOR_V1_0_CPP_1_SRC_GRAPHALGORITHMS_LEASTSPANNINGTREEENGINE_LEASTSPANNINGTREEENGINE_H_
